language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  include:
    - php: hhvm
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.0
  fast_finish: true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

notifications:
  email: true
